// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4n67x3nebsw24AAbU-TrrCYw1iUfhdt0',
    appId: '1:952903534436:web:ad32849ec5cc2827445c71',
    messagingSenderId: '952903534436',
    projectId: 'tybatest-a87cd',
    authDomain: 'tybatest-a87cd.firebaseapp.com',
    storageBucket: 'tybatest-a87cd.appspot.com',
    measurementId: 'G-E5K3RFBZJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3uuRnyB44aj0eRoErQ70q_E5f4jORCP8',
    appId: '1:952903534436:android:970849f57c860175445c71',
    messagingSenderId: '952903534436',
    projectId: 'tybatest-a87cd',
    storageBucket: 'tybatest-a87cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoleM3eCUCMv7pZByO_bycSEJFTboOZWE',
    appId: '1:952903534436:ios:a6891973e3d92f0d445c71',
    messagingSenderId: '952903534436',
    projectId: 'tybatest-a87cd',
    storageBucket: 'tybatest-a87cd.appspot.com',
    iosClientId: '952903534436-sith20ppuvcl0gqrdm6ufm2957mkslf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.typaFrontend',
  );
}
